# baseURL = 'blog-space-ten.vercel.app'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
title = 'DvdBr3o'
theme = [ 'stack', 'admonitions' ]

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    # hl_Lines = ""
    lineAnchors = ""
    lineNoStart =1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4